name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          
          pip install pipenv
          cd backend
          pipenv install --dev
          pipenv run python -m build

      - name: Install Surge
        run: pipenv run npm install -g surge

      - name: Deploy to Surge
        run: |
          cd backend
          ls -l ./dist
          pipenv run surge ./dist weatherapphassanbe.surge.sh --token ${{ secrets.SURGE_TOKEN }}
