name: Full Stack Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-full-stack:
    runs-on: ubuntu-latest
    needs:
      - deploy-frontend
      - deploy-backend
    steps:
      - name: Trigger Frontend Deployment
        run: echo "Triggered Frontend Deployment"
        uses: actions/github-script@v7
        with:
          script: |
            workflow_id=$(echo "${{ github.event.inputs.workflow_id }}" | jq -r .workflow_id)
            repo="${{ github.repository }}"

            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${repo}/actions/workflows/${workflow_id}/dispatches" \
              -d '{"ref":"main"}'
      - name: Trigger Backend Deployment
        run: echo "Triggered Backend Deployment"
        uses: actions/github-script@v7
        with:
          script: |
            workflow_id=$(echo "${{ github.event.inputs.workflow_id }}" | jq -r .workflow_id)
            repo="${{ github.repository }}"

            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${repo}/actions/workflows/${workflow_id}/dispatches" \
              -d '{"ref":"main"}'
