name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install npm
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Run surge
        run: |
          cd frontend
          surge ./build weatherAppHassan.surge.sh --token ${{ secrets.SURGE_TOKEN }}
