name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying Backend and Frontend to Surge
    env:
      CI: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install npm and Build React App
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy Backend and Frontend with Surge
        run: |
          surge ./frontend/build weatherAppHassan.surge.sh --token ${{ secrets.SURGE_TOKEN }}
          cd backend
          pipenv install --dev --python 3.8.10
          pipenv shell
          python3 main.py
