name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying Backend and Frontend to Surge
    env:
      CI: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install npm and Build React App
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy Backend and Frontend with Surge
        run: |
          surge ./frontend/build weatherAppHassan.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use a version available in the cache, e.g., 3.8 or 3.9

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install Dependencies and Run Flask App
        run: |
          cd backend
          pipenv install --dev
          pipenv run python3 main.py
